/**
 * Typed access to the benchmark data published by the ai-benchmark harness.
 *
 * `src/data/lab.json` is generated by `pnpm bench publish` in that repo and
 * copied here. Nothing on this site computes scores; it only renders them.
 */
import labData from '../data/lab.json';

export type LabCriterion = {
	id: string;
	label: string;
	weight: number;
	score: number;
	rationale: string;
};

/**
 * A signal the harness measured and published but deliberately excluded from
 * the score, because it proved unstable across repeat runs of the same build.
 */
export type LabObservation = {
	id: string;
	label: string;
	value: boolean | number | string | null;
	status: 'pass' | 'fail' | 'info' | 'skipped';
	detail: string | null;
};

export type LabRun = {
	slug: string;
	agent: string;
	model: string | null;
	reasoning: string | null;
	ranAt: string;
	total: number;
	band: 'gate-failed' | 'thin' | 'partial' | 'strong' | 'exceptional';
	gatePassed: boolean;
	gateFailedAt: string | null;
	criteria: LabCriterion[];
	observations: LabObservation[];
	buildBytes: number;
	playable: string | null;
	shots: string[];
};

export type LabBenchmark = {
	id: string;
	name: string;
	summary: string;
	category: string;
	difficulty: string;
	rubricId: string;
	scorerVersion: string;
	runs: LabRun[];
};

const lab = labData as unknown as {
	version: number;
	generatedAt: string;
	benchmarks: LabBenchmark[];
};

export const benchmarks = lab.benchmarks;
export const generatedAt = lab.generatedAt;

export function getBenchmark(id: string) {
	return benchmarks.find((benchmark) => benchmark.id === id);
}

/** Display name for a run: the model where known, otherwise the agent's default. */
export function runLabel(run: LabRun) {
	return run.model ?? `${run.agent} (default)`;
}

export const stats = {
	benchmarks: benchmarks.length,
	runs: benchmarks.reduce((total, benchmark) => total + benchmark.runs.length, 0),
	playable: benchmarks.reduce(
		(total, benchmark) => total + benchmark.runs.filter((run) => run.playable).length,
		0,
	),
	models: new Set(benchmarks.flatMap((b) => b.runs.map(runLabel))).size,
};

/** Score bands drive colour everywhere, so the thresholds live in one place. */
export function bandColour(band: LabRun['band']) {
	switch (band) {
		case 'exceptional':
		case 'strong':
			return 'var(--lab-strong)';
		case 'partial':
			return 'var(--lab-partial)';
		case 'thin':
			return 'var(--lab-thin)';
		default:
			return 'var(--lab-dead)';
	}
}

/** Every model that appears anywhere, with its best score per benchmark. */
export function standings() {
	const rows = new Map<string, { label: string; agent: string; byBenchmark: Map<string, LabRun> }>();
	for (const benchmark of benchmarks) {
		for (const run of benchmark.runs) {
			const label = runLabel(run);
			const row = rows.get(label) ?? { label, agent: run.agent, byBenchmark: new Map() };
			const existing = row.byBenchmark.get(benchmark.id);
			if (!existing || run.total > existing.total) row.byBenchmark.set(benchmark.id, run);
			rows.set(label, row);
		}
	}
	return [...rows.values()].sort((a, b) => {
		const best = (row: typeof a) => Math.max(...[...row.byBenchmark.values()].map((r) => r.total), 0);
		return best(b) - best(a);
	});
}
